fos_rest:
  param_fetcher_listener:  force
  body_listener: true
  view:
    view_response_listener: true
  exception:
    enabled: true

  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
