nelmio_api_doc:
    documentation:
        info:
            title: Dutch Auction
            description: Dutch Auction based on symfony framework
            version: 0.1.0
    areas:
        path_patterns:
        - ^/api(?!/doc$)
